#!/bin/sh

# Install software
sudo apt-get install build-essential -y

sudo apt-get install cmake libhdf5-dev libblas-dev liblapack-dev libatlas-base-dev libjasper-dev libqtgui4 libqttest4-perl -y

pip3 install numpy
pip3 install scipy
pip3 install matplotlib
pip3 install h5py
pip3 install pydot
pip3 install opencv-contrib-python
pip3 install "picamera[array]"
pip3 install scikit-image
pip3 install scikit-learn

pip3 install https://github.com/lhelontra/tensorflow-on-arm/releases/download/v1.12.0/tensorflow-1.12.0-cp35-none-linux_armv7l.whl

sudo apt-get install mplayer -y

sudo apt-get install espeak -y

# reboot
sudo reboot
