#!/bin/sh

# Install software
sudo apt-get install cmake libhdf5-dev python-opencv python-scipy python-matplotlib python-h5py python-pydot

sudo apt-get install libblas-dev liblapack-dev python-dev libatlas-base-dev gfortran python-setuptools

sudo pip install http://ci.tensorflow.org/view/Nightly/job/nightly-pi/lastSuccessfulBuild/artifact/output-artifacts/tensorflow-1.5.0-cp27-none-any.whl -U

sudo pip install keras

sudo pip install "picamera[array]"

sudo apt-get install mplayer

sudo apt-get install espeak

# reboot
sudo reboot
